// Live-mode incident data for fn-connect STOCK_CODE_010 incident.
// Swapped in by loadLiveData() to replace mock deploy diff + metrics.

export const liveDeployDiff = [
  '=== DEPLOYED CODE — release/2026.05.20 (fn-connect 2026.05.20.2) ===',
  'This is what was running when the incident occurred.',
  '',
  'Release: release/2026.05.20 | fn-connect: 2026.05.20.2',
  'DB changes: Connect (release/2026.05.20) · Platform (release/2026.05.20)',
  'Release steps: DB scripts for connect → Redis cache refresh → Deploy fn-connect',
  '  → Deploy fn-identity → chip1 DB script → chip1-account → chip1-mc1-core',
  '  → chip1-transaction → chip1-crm-webui → chip1-webui',
  '',
  'Components: MC1 Core 2026.05.20.0 · Account 2026.05.20.0 · Transaction 2026.05.20.1',
  '  CRM WebUI 2026.05.20.3 · WebUI 2026.05.20.0 · fn-identity 2026.05.20.0 · fn-connect 2026.05.20.2',
  '',
  '--- Buggy code in EntityIdMappingUtil.java (running at time of incident) ---',
  '',
  '  // Contact entity ID lookup used during stock code sync to resolve XCRM PO/contact IDs',
  '  Optional<EntityIdMapping> contactFromAccountOptional =',
  '      entityIdMappingRepository.findUnifiedEntityMappingInfoByParent(',
  '          sourceBusinessId, CONTACT, contactId, accountId);',
  '  return contactFromAccountOptional',
  '      .map(entityIdMapping -> getOtherId(contactId, entityIdMapping))',
  '      .map(Pair::getRight)',
  '      .orElse(null);',
  '',
  '  // BUG: findUnifiedEntityMappingInfoByParent returns wrong record for accounts',
  '  // with duplicate contacts in entity_id_mapping.',
  '  // getOtherId() on wrong mapping resolves to invalid XCRM entity ID (0 or null)',
  '  // -> XCRM-prod rejects: STOCK_CODE_010: Invalid PO id - 0 or PO line id - 0',
  '',
  '=== FIX APPLIED — release/2026.05.21 (PR #355 "duplicate contact handling") ===',
  '',
  'diff --git a/src/main/java/co/altir/repository/EntityIdMappingRepository.java',
  '@@ -288,6 +288,66 @@',
  '+  @Query(value = "SELECT * FROM entity_id_mapping WHERE ... UNION ALL ...",',
  '+      nativeQuery = true)',
  '+  List<EntityIdMapping> findAllUnifiedEntityMappingInfoByParent(',
  '+      String businessId, String entityType, String entityId, String parentEntityId);',
  '',
  'diff --git a/src/main/java/co/altir/util/EntityIdMappingUtil.java',
  '@@ -590,12 +590,29 @@',
  '-    Optional<EntityIdMapping> contactFromAccountOptional =',
  '-        entityIdMappingRepository.findUnifiedEntityMappingInfoByParent(',
  '+    List<EntityIdMapping> contactListFromAccount =',
  '+        entityIdMappingRepository.findAllUnifiedEntityMappingInfoByParent(',
  '             sourceBusinessId, CONTACT, contactId, accountId);',
  '-    return contactFromAccountOptional',
  '-        .map(entityIdMapping -> getOtherId(contactId, entityIdMapping))',
  '-        .map(Pair::getRight)',
  '-        .orElse(null);',
  '+    if (notEmpty(contactListFromAccount)) {',
  '+      contactListFromAccount.sort(',
  '+          Comparator.comparing(EntityIdMapping::getCreatedTimestamp).reversed());',
  '+      EntityIdMapping mapping = contactListFromAccount.get(0);',
  '+      if (contactListFromAccount.size() > 1) {',
  '+        log.warn("Found Duplicate Contacts For Account Id: {} & ContactId: {}",',
  '+            accountId, contactId);',
  '+      }',
  '+      return getOtherId(contactId, mapping).getRight();',
  '+    }',
  '+    return null;',
  '   }',
].join('\n')

// fn-connect error counts from Loki (count_over_time 2m window) — real data 2026-05-21
// Baseline ~950/2min, spike starts 20:36, peaks 20:38 and 20:56-21:00
export const liveMetrics = [
  { time: '20:00', errorRate: 966 },
  { time: '20:02', errorRate: 982 },
  { time: '20:04', errorRate: 998 },
  { time: '20:06', errorRate: 807 },
  { time: '20:08', errorRate: 932 },
  { time: '20:10', errorRate: 906 },
  { time: '20:12', errorRate: 726 },
  { time: '20:14', errorRate: 880 },
  { time: '20:16', errorRate: 854 },
  { time: '20:18', errorRate: 1000 },
  { time: '20:20', errorRate: 869 },
  { time: '20:22', errorRate: 910 },
  { time: '20:24', errorRate: 904 },
  { time: '20:26', errorRate: 963 },
  { time: '20:28', errorRate: 941 },
  { time: '20:30', errorRate: 991 },
  { time: '20:32', errorRate: 955 },
  { time: '20:34', errorRate: 1062 },
  { time: '20:36', errorRate: 2275 },
  { time: '20:38', errorRate: 2549 },
  { time: '20:40', errorRate: 1443 },
  { time: '20:42', errorRate: 1131 },
  { time: '20:44', errorRate: 1128 },
  { time: '20:46', errorRate: 1267 },
  { time: '20:48', errorRate: 1775 },
  { time: '20:50', errorRate: 1719 },
  { time: '20:52', errorRate: 1215 },
  { time: '20:54', errorRate: 1458 },
  { time: '20:56', errorRate: 2818 },
  { time: '20:58', errorRate: 3485 },
  { time: '21:00', errorRate: 3397 },
]
